
[h5chat] 

pg_db_url = "postgres://postgres:123456@localhost:5432/h5chat"
redis_url = "redis://localhost:6379"
main_port = 8080
pool_threads = 4
pg_db_pool_threads = 4
redis_pool_threads = 1

base_url = "http://127.0.0.1"
#base_url = "http://h5chat.com"


to_test_num = 9999
to_test_str = "hello, world!"
